### ISSUE TITLE
`/bin/sh` output is not what expected

### ISSUE THREAD

**Issue by the-ssd** [zhiburt/ptyprocess#15]
expectation:
```
sh-5.1$ echo test
test
```
reality:
```
sh-5.1$ 
test
```
(this works with fish instead of sh)

also when starting shell without writing anything to it, you would expect
```
sh-5.1$
```
but instead it is empty (same on fish)

this is important for ssh, which is what I am trying to do
there is `portabe-pty` (I am currently using it), but it has a lot of dependencies (includes nix)
and because I am writing it for Redox OS
I will need to port multiple dependencies, some of which are 4–6 years old

while for `ptyprocess` it's just nix (still needs porting)
if you could fix these 2 problems it will be really helpful :)

**Comment by zhiburt** [comment]
Hi @the-ssd could you provide the code your using?

**Comment by zhiburt** [comment]
PS: I've also had some plans to make a SSH api https://github.com/zhiburt/expectrl/issues/23, but after looking through some analogues I got to worry that it's harder then it seems.

**Comment by the-ssd** [comment]
```
use std::thread;
use std::time::Duration;
use ptyprocess::PtyProcess;
use std::io::{BufReader, Result, Write, Read};
use std::process::Command;


fn main() -> Result<()> {
    // spawn a cat process
    let process = PtyProcess::spawn(Command::new("/bin/sh"))?;

    // stream for reading
    let stream = process.get_raw_handle()?;
    // thread for reading (needed for ssh to work)
    thread::spawn(move || {
        let mut reader = BufReader::new(stream);

        loop {
            let mut buf = [0; 1];
            let _ = reader.read_exact(&mut buf);
            // in ssh this would be set data to client
            print!("{}", String::from_utf8_lossy(&buf));
        }

    });

    // create a new communication stream for writing
    let mut stream = process.get_raw_handle()?;

    thread::sleep(Duration::from_secs(1));
    // send a message to process
    writeln!(stream, "echo test")?;

    // wait to read output from the stream
    thread::sleep(Duration::from_secs(1));

    Ok(())
}
```

**Comment by the-ssd** [comment]
Also, I have a working ssh server, but I am having problems with the client

**Comment by zhiburt** [comment]
So I've seemed to figured it out.
You can do the following.

```rust
    let mut process = PtyProcess::spawn(Command::new("/bin/sh"))?;
    process.set_echo(true, None).unwrap();
```

**Comment by zhiburt** [comment]
PS: I'd recommend you to use [`expectrl`](https://github.com/zhiburt/expectrl/) instead if you need a high level API.

**Comment by the-ssd** [comment]
Thanks, this solved the first problem, but there is still the other one
```
use std::thread;
use std::time::Duration;
use ptyprocess::PtyProcess;
use std::io::{BufReader, Result, Write, Read};
use std::process::Command;


fn main() -> Result<()> {
    // spawn a process
    let mut process = PtyProcess::spawn(Command::new("/bin/sh"))?;
    process.set_echo(true, None).unwrap();
    

    // stream for reading
    let stream = process.get_pty_stream()?;
    // thread for reading (needed for ssh to work)
    thread::spawn(move || {
        let mut reader = BufReader::new(stream);

        loop {
            let mut buf = [0; 1];
            let _ = reader.read_exact(&mut buf);
            // in ssh this would be set data to client
            print!("{}", String::from_utf8_lossy(&buf));
        }

    });
    
    // wait to read output from the stream
    thread::sleep(Duration::from_secs(5));

    Ok(())
}
```
this should return `sh-5.1$` before the program exits (in this case before 5 sec delay)
but instead it is empty

**Comment by zhiburt** [comment]
works for me?

```log
   Compiling ptyprocess v0.4.1 (/home/maxim/projects/ptyprocess)
warning: unused import: `Write`
 --> examples/ssh.rs:4:34
  |
4 | use std::io::{BufReader, Result, Write, Read};
  |                                  ^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

warning: `ptyprocess` (example "ssh") generated 1 warning (run `cargo fix --example "ssh"` to apply 1 suggestion)
    Finished dev [unoptimized + debuginfo] target(s) in 0.27s
     Running `target/debug/examples/ssh`
sh-5.1$ 
```

**Comment by zhiburt** [comment]
PS: I am not sure what you're trying to achieve with additional thread. But you could use `expectrl` here as follows.

```rust
use expectrl::repl::ReplSession;

fn main() {
    let mut p = expectrl::spawn("sh").unwrap();
    p.get_process_mut().set_echo(true, None).unwrap();

    let mut shell = ReplSession::new(p, String::from("sh-5.1$"), Some(String::from("exit")), true);

    shell.expect_prompt().unwrap();

    let output = exec(&mut shell, "echo Hello World");
    println!("{:?}", output);

    let output = exec(&mut shell, "echo '2 + 3' | bc");
    println!("{:?}", output);
}

fn exec(shell: &mut ReplSession, cmd: &str) -> String {
    let buf = shell.execute(cmd).unwrap();
    let mut string = String::from_utf8_lossy(&buf).into_owned();
    string = string.replace("\r\n\u{1b}[?2004l\r", "");
    string = string.replace("\r\n\u{1b}[?2004h", "");

    string
}
```

```log
"Hello World"
"5"
```

**Comment by the-ssd** [comment]
Some shells have autocomplete to `expectrl` won't work :(
reading from a stream is going to block the thread, so an extra thread is needed
but writing is ok

try changing 5 to 99999 in sleep
or remove the thread

it will be empty then write `sh-5.1$` and exit
but it should write `sh-5.1$` then wait and exit

**Comment by zhiburt** [comment]
>it will be empty then write sh-5.1$ and exit
but it should write sh-5.1$ then wait and exit

True 

But not exactly, I've just got to remember that terminals often do some buffering. 
So to see what you want to just change `print!` to `println!`.

> Some shells have autocomplete to expectrl won't work :(

Sorry, I don't get it, could you explain a bit?
I mean some have autocomplete but then what?

**Comment by the-ssd** [comment]
So to run a remote shell that has autocomplete, I can't just wait for the full command because then autocomplete doesn't work.
Each input (key) is received separately and has to be written to pty.
Reading has to be done is a separate thread because of blocking.

Changing `print!` to `println!` worked, thanks!
```rust
std::io::stdout().flush().unwrap(); // this also worked
```
