### ISSUE TITLE
Some output doesn't appear in ptyprocess

### ISSUE THREAD

**Issue by GaryBoone** [zhiburt/ptyprocess#4]
Some commands generate output that `ptyprocess` doesn't show. The Python `input` command is one. Try this in a shell:

    $ python3 -c 'yn=input("Agree?"); print("answer was " + yn)'

The command prints a prompt, awaits input, then writes it. However, when run via `ptyprocess`, nothing is shown. Here's some code showing the problem. The results are 1) the `Name?` prompt is not shown, and 2) typing something and hitting return doesn't appear to have any effect, and 3) the expected output `Your name is ` is not printed. 

    use ptyprocess::PtyProcess;
    use std::process::Command;
    // python3 -c 'yn=input("Agree?"); print("answer was " + yn)'

    fn main() {

        use ptyprocess::WaitStatus;
        use std::io::{stdout, Write};
        use std::{thread, time::Duration};

        let mut cmd = Command::new("python3");
        // These args make it print as expected.
        //cmd.args(vec!["-c", "print('Hello, '); print('world')"]);
        // These args make it print nothing.
        //cmd.args(vec!["-c", "yn=input('Agree?'); print('answer was ' + yn)"]);
        // These args make it print only 'Hello'.
        cmd.args(vec!["-c", "print('Hello'); yn=input('Agree?'); print('answer was ' + yn)"]);

        let mut process = PtyProcess::spawn(cmd).unwrap();

        let mut buf = vec![0];
        loop {
            match process.try_read_byte() {
                Ok(None) => {}
                Ok(Some(Some(c))) => {
                    buf[0] = c;
                    stdout().write(&buf).unwrap();
                    process.flush().unwrap();
                }
                Ok(Some(None)) => {
                    println!("rec'd Some(None). Done");
                    break;
                }
                Err(e) => {
                    println!("err: {}", e);
                    break;
                }
            }
            thread::sleep(Duration::from_micros(100));
        }

        match process.wait() {
            Ok(WaitStatus::Exited(pid, status)) => {
                println!("child process {} exited with: {:?}", pid, status);
            }
            Ok(ws) => {
                println!("process state is: {:?}", ws);
            }
            Err(e) => println!("error attempting to process.wait: {}", e),
        }
    }

**Comment by zhiburt** [comment]
Hey @GaryBoone thanks for reporting it.

I'll try to tackle it tomorrow.

**Comment by zhiburt** [comment]
I would imagine it may be related to #3

**Comment by zhiburt** [comment]
My guess that input waits before you actually input something.
`send`/`write` to `PtyProcess`. Why a prompt isn't shown? (yet don't know)

**Comment by zhiburt** [comment]
So I checked it.
Here's a working example.

```rust
// python3 -c 'yn=input("Agree?"); print("answer was " + yn)'

use ptyprocess::PtyProcess;
use std::{io::Read, process::Command};

fn main() {
    use std::io::{stdout, Write};

    let mut cmd = Command::new("python3");
    cmd.args(vec!["-c", "yn=input('Agree?'); print('answer was ' + yn)"]);

    let mut process = PtyProcess::spawn(cmd).unwrap();

    let mut buf = [0; 128];
    let n = process.read(&mut buf).unwrap();

    assert_eq!(String::from_utf8_lossy(&buf[..n]), "Agree?");
    write!(process, "123\n").unwrap();

    let n = process.read(&mut buf).unwrap();
    assert_eq!(String::from_utf8_lossy(&buf[..n]), "answer was 123\r\n");
}
```

Essentially I think something is going on with try_read - meaning I can't state why it wasn't reading...

It's night now so probably tomorrow is a better time.

**Comment by zhiburt** [comment]
By the way the same code using expectrl.

```rust
// python3 -c 'yn=input("Agree?"); print("answer was " + yn)'

use expectrl::Session;
use std::{io::Write, process::Command};

fn main() {
    let mut cmd = Command::new("python3");
    cmd.args(vec!["-c", "yn=input('Agree?'); print('answer was ' + yn)"]);

    let mut session = Session::spawn_cmd(cmd).unwrap();

    session.expect("Agree?").unwrap();
    session.write_all(b"Yes\n").unwrap();
    session.expect("answer was Yes").unwrap();
}
```

**Comment by zhiburt** [comment]
BTW expect underthehood using `try_read` ....

**Comment by GaryBoone** [comment]
Ah, thanks for that quick and thorough reply. I see that it works, but solves a slightly different problem. In the above code in the comment beginning with "So I checked it" and the last comment, the program writes to the stdin of the spawned program. What I noticed in the original issue at the top is that the interactivity of the user breaks with `ptyprocess`. Specifically, what is expected in the program I posted is that, when run:

1. The user sees the prompt, "Agree?"
2. The user types an answer, say "y".
3. The program displays. "answer was y".

So that's different from the examples below where the code provides the answers. In particular, the issue seems to be that the interactivity isn't working. The user can't see the prompt or provide the input. 

Here's a simple program to demonstrate how it would work with the right interactivity:

    fn main() {
        let status = Command::new("python3")
            .args(vec!["-c", "yn=input('Agree? '); print('answer was: ' + yn)"])
            .status()
            .expect("failed to execute process");

        println!("process finished with: {}", status);
    }

If you try it, you see the prompt, can enter a response, and then see the answer. However, in this case, the program doesn't receive the answer!

**Comment by zhiburt** [comment]
So you're basically saying you wan't to `interact` with that program correct?

If you are, your got lucky as yesterday I've added a `similar` method.

Check it out.

**Comment by GaryBoone** [comment]
Yes, that works for the python example in that the interactivity is right. 

To be more clear, I want to allow interactions with the running program while also processing the lines that are printed to stdout/stderr. The first code above shows how to `try_read()` each character so it can be processed. It works for non-interactive binaries, but not interactive ones as we discussed.

So next, I'll have to try coding with `process.interact()` to see if I can be in interactive mode and also `try_read` the outputs and process them. There's no way to know when a user has been asked for input by a given binary, so the `process.interact()` will have to be running always once the `ptyprocess` spawns.

**Comment by zhiburt** [comment]
> There's no way to know when a user has been asked for input by a given binary

I don't think its possible to track such things.

> To be more clear, I want to allow interactions with the running program while also processing the lines that are printed to stdout/stderr. The first code above shows how to try_read() each character so it can be processed. It works for non-interactive binaries, but not interactive ones as we discussed.

I see.
I actually think your initial example is almost right, beside the fact that you wasn't expected to handle an input.
But try_read function works unexpectedly. As I was thinking that continues calls to it is fine but it seems not...

(Actually as I understand with a bit of a sleep it will work. So Basically your initial example with handling of input got to work)

> So next, I'll have to try coding with process.interact() to see if I can be in interactive mode and also try_read the outputs and process them.

As I understand you won't as `interact` is basically blocks until you type an escape character `CTRL-]`

I'll try to spend some time tomorrow according to your initial style.

**Comment by zhiburt** [comment]
Well I checked `try_read` works fine.

> To be more clear, I want to allow interactions with the running program while also processing the lines that are printed to stdout/stderr. The first code above shows how to try_read() each character so it can be processed. It works for non-interactive binaries, but not interactive ones as we discussed.

One more time, I think it will be easier for you to switch to `expectrl` and run `expect` function to wait before some output.

Could you one more time speak out if you have any issue, cause I started to think the issue is resolved?

**Comment by zhiburt** [comment]
test 1ca94c7379c837bf9dea709b071831fe7163cecf

**Comment by GaryBoone** [comment]
Ok, switching to `expectrl` per advice. Closing this issue. [And thanks for working with me!]
