### ISSUE TITLE
No exit status if a command exits during process.interact()

### ISSUE THREAD

**Issue by GaryBoone** [zhiburt/ptyprocess#5]
There appears to be no way to retrieve the exit status of a command that enters `interact()` if it exits while in `interact()`.

In a shell:
    $ python3 -c 'yn=input("Agree?"); print("answer was " + yn)'; echo "exit code: $?"
   Agree?y
   answer was y
   exit code: 0

Repro:

    fn main() {
        let mut cmd = Command::new("python3");
        cmd.args(vec!["-c", "yn=input('Agree?'); print('answer was ' + yn)"]);
        let mut process = PtyProcess::spawn(cmd).unwrap();
        process.interact().unwrap();
        println!("status {:?}", process.status());
    }

The output is:

    Agree?y
    answer was y
    status Err(Sys(ECHILD))

It would be expected that `process.status())` would provide the exit result, but it returns an error because the process is already gone by the time it is called. 

The problems appears to be here: https://github.com/zhiburt/ptyprocess/blob/57278cd3fb0021540faaf0754eb7cfb014cedfa2/src/process.rs#L388

            if matches!(self.is_alive(), Ok(false)) {
                return Ok(());
            }

The interactive mode only checks for aliveness, returning on `()` if the child process completes. Shouldn't it return the exit code if the process has completed?

I notice in my other code (in the first comment of issue https://github.com/zhiburt/ptyprocess/issues/4) that I had `try_read()` loops followed by 

    match process.wait() {
        Ok(WaitStatus::Exited(pid, status)) => {
          println!("child process {} exited with: {:?}", pid, status);
          ...

That works because when the process ends, it first closes stdout/stderr, then sets the exit code. The above works because the `try_read()` loop breaks on `Ok(Some(None))`, which is how `ptyprocess` indicates that the pipe has closed. So the code can then enter the `match process.wait() {` fast enough to catch the exit status of process. It works even for processes that don't write to stdout because we still open a stdout pipe for them for `try_read()`. This approach works, but sounds like a race condition. Maybe there's a better way? In the issue reported here, since the `interact()` controls the stdout/stderr pipes, we don't know when they're closed. How do we obtain the exit status?

**Comment by zhiburt** [comment]
> The interactive mode only checks for aliveness, returning on () if the child process completes. Shouldn't it return the exit code if the process has completed?

I think it makes sense.

**Comment by zhiburt** [comment]
Done 51b837e0ce72800fe19442f6dc21ae8b93d280f3

But I started to think that `interact` function is surely not responsibility of `ptyprocess` library. (I was thinking about it when it was created as well. The reason why it's here is because `Stream` structure is private.)

I do intend to move it to `expectrl`.

**Comment by zhiburt** [comment]
Moved to `expectrl` a54f50e4a9ebbc7b9e6ab377f3b1821a02b792bc

**Comment by GaryBoone** [comment]
Ok, moving to `expectrl` obviates this issue. Closing.
