### ISSUE TITLE
No `Some(None)` for `try_read_byte` on close for Linux

### ISSUE THREAD

**Issue by GaryBoone** [zhiburt/ptyprocess#7]
It appears that `Some(None)` is not being generated on Linux for `try_read_byte`.

Here's the demo program:

    use ptyprocess::PtyProcess;
    use std::io::{stdout, Write};

    fn main() {
        let cmd = std::process::Command::new("ls");
        let mut process = PtyProcess::spawn(cmd).unwrap();
        let mut buf = vec![0; 200];
        loop {
            match process.try_read_byte() {
                Ok(None) => {}
                Ok(Some(Some(c))) => {
                    buf.push(c);
                    if c == 10 || c == 13 {
                        stdout().write_all(&buf).unwrap();
                        stdout().flush().unwrap();
                        // Process current buffer...
                        buf.clear();
                    }
                }
                Ok(Some(None)) => {
                    println!("rec'd Some(None). process stdout closed");
                    break;
                }
                Err(e) => {
                    println!("try_read_byte error: {}", e);
                    break;
                }
            }
        }
        println!("completed reading command");
    }

On macOs, it behaves as expected:

    cargo run
        Finished dev [unoptimized + debuginfo] target(s) in 0.02s
         Running `target/debug/try_read_bytes`
    Cargo.lock	Cargo.toml	src		target
    rec'd Some(None). process stdout closed
    completed reading command

But on Linux, it seems to write correctly and completely, but `Some(None)` is not seen. So then there's an error on the next `try_read_byte` on the closed file:

    $ cargo run
        Finished dev [unoptimized + debuginfo] target(s) in 0.01s
         Running `target/debug/try_read_bytes`
    Cargo.lock  Cargo.toml  src  target
    try_read_byte error: Input/output error (os error 5)
    completed reading command

**Comment by zhiburt** [comment]
Hi @GaryBoone thank you for the report.

It's actually interesting because we handle this error exactly as Some(None).
Could you tell what distribution you're using? And which version of `ptyprocess` are you using?

https://github.com/zhiburt/ptyprocess/blob/29d4a7e5e3f2e0d2fa575e174add646e5268f3c0/src/stream.rs#L314-L316

By the way on my machine I get what is expected.

```
[mzhiburt@fedora ptyprocess]$ lsb_release -a
LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: Fedora
Description:    Fedora release 34 (Thirty Four)
Release:        34
Codename:       ThirtyFour
```

```
Cargo.lock  Cargo.toml  examples  LICENSE  README.md  src  target  tests
rec'd Some(None). process stdout closed
completed reading command
```

**Comment by zhiburt** [comment]
I am not sure if the code renders your real intentions but as I understand it reads by line.
Which can be done in a slightly different manner.

```rust
fn main() {
    let cmd = std::process::Command::new("ls");
    let mut process = PtyProcess::spawn(cmd).unwrap();
    loop {
        let mut line = String::new();
        match process.read_line(&mut line) {
            Ok(0) => {
                println!("rec'd Some(None). process stdout closed");
                break;
            }
            Ok(_) => {
                let _ = write!(stdout(), "{}", line).unwrap();
            }
            Err(e) => {
                println!("try_read_byte error: {}", e);
                break;
            }
        }
    }
    println!("completed reading command");
}
```

```
Cargo.lock  Cargo.toml  examples  LICENSE  README.md  src  target  tests
rec'd Some(None). process stdout closed
completed reading command
```

**Comment by GaryBoone** [comment]
The Linux distribution I'm using is a corporate derivative of Debian.

From Cargo.toml:

    [dependencies]
    expectrl = {git = "https://github.com/zhiburt/expectrl"}
    ptyprocess ={git = "https://github.com/zhiburt/ptyprocess"}


In the code example, I have to read by character by character to catch terminal line ends. The command I need to watch can emit `\r` to overwrite the current line instead of `\r\n` to start a new line. 

Perhaps a workaround would be to add a parameter to `read_line()` that instructs it _not_ to drop line endings?

**Comment by zhiburt** [comment]
Could I ask you to change your example to print a Debug version of error, and publish the output?

```
// Change this
// println!("try_read_byte error: {}", e);
// To this
// println!("try_read_byte error: {:?}", e);
```

> In the code example, I have to read by character by character to catch terminal line ends. The command I need to watch can emit \r to overwrite the current line instead of \r\n to start a new line.

I see,
Yes in such scenario it's worthwhile to use `try_read_*`.

> Perhaps a workaround would be to add a parameter to read_line() that instructs it not to drop line endings?

I'd not do that as we get read_line method from `std::io::BufRead` trait.
But what I could suggest is to use `expectrl` (one more time :smile:)

Something like this. But yes it's a bit different approach. 

```rust
let result = p.expect(Any(vec![Box::new("\r"), Box::new("\n"), , Box::new(EOF)]);
```
